### ISSUE TITLE
[blog] tables are not scrollable on mobile

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2454]
See table in https://blog.amp.dev/2018/10/08/how-to-make-amp-even-faster/

**Comment by westonruter** [comment]
@sebastianbenz I've added:

```css
.entry-content table {
	overflow-x: auto;
}
```

Does that work for you?
