### ISSUE TITLE
Don't use content property in keyframes

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2686]
This is why we can't extract keyframes into a separate style block:

`WARNING Found invalid keyframe property 'content' in 'highlight-code' not moving to style[amp-keyframes]`

@sebil can you find out if we can avoid it?

**Comment by sebil** [comment]
That's not the only one: 

/about/websites/
`WARNING Found invalid keyframe property 'background-position' in 'gradientChange' not moving to style[amp-keyframes]`

I found that `gradientChange` keyframes where never used, so I removed them.

---

The other one is caused by the format-visual with the sidebar animation (see below)

![ezgif com-optimize](https://user-images.githubusercontent.com/22053023/62371028-06e35780-b534-11e9-9d1a-cbb8c8e330cb.gif)

The values `side="left"` and `"right"` are the contents of a pseudo-element inside the code-snippet and changing in a big chain of keyframes:

```scss
@keyframes highlight-code {
  0%, 90%, 100% { content: 'right'; background-color: transparent; }
  9%            { content: 'right'; background-color: color('pink-flamingo'); }
  18%           { content: " ";     background-color: color('pink-flamingo'); }
  36%           { content: 'left';  background-color: color('pink-flamingo'); }
  45%, 54%      { content: 'left';  background-color: transparent; }
  63%           { content: 'left';  background-color: color('pink-flamingo'); }
  72%           { content: " ";     background-color: color('pink-flamingo'); }
  81%           { content: 'right'; background-color: color('pink-flamingo'); }
}
```

I can refactor that with real elements (not pseudo) and try it with hide and show or something.

I'll let you know.

**Comment by sebil** [comment]
Fixed this know with custom elements and just opacity.

Result:

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/22053023/62391643-acfb8580-b565-11e9-880f-1ed674e442cf.gif)

Keyframes:
```scss
@keyframes handleValueRight {
  0%, 18% { opacity: 1; }
  18.01%, 81% { opacity: 0; }
  81.01%, 100% { opacity: 1; }
}

@keyframes handleValueEmpty {
  0%, 18% { opacity: 0; }
  18.01%, 36% { opacity: 1; }
  36.01%, 72% { opacity: 0; }
  72.01%, 81% { opacity: 1; }
  81.01%, 100% { opacity: 0; }
}

@keyframes handleValueLeft {
  0%, 36% { opacity: 0; }
  36.01%, 72% { opacity: 1; }
  72.01%, 100% { opacity: 0; }
}

@keyframes handleCodeMarker {
  0% { opacity: 0; }
  9%, 36% { opacity: 1; }
  45%, 54% { opacity: 0; }
  63%, 81% { opacity: 1; }
  90%, 100% { opacity: 0; }
}
```

PR is on the way
