### ISSUE TITLE
Version toggle is not shown for translations

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2963]
## Problem

Currently the importer adds the version information to all imported components.
* List of all versions
* File version
* A flag that shows the file is the latest version
* A special path mapping if the file is the latest version

That is fine as long as all documentation is imported.
But when we have translated documentation the version information is not updated!

As a result the version information is not available for the current translated files:
https://amp.dev/es/documentation/components/amp-carousel-v0.1/?format=websites

## Possible solution

It would be best, if the single files would not contain more than the file version.
In that case the translated files would not have to change when a new version is available.

A possible solution might be to put each component documentation into their own folder and set the version information in the `_blueprint.yaml`

The folder structure could be as follows:
![image](https://user-images.githubusercontent.com/6458408/64859517-bed34c80-d62a-11e9-843a-3ad312d41d18.png)

The `_blueprint.yaml` could look like this:
```yaml
$path: /documentation/components/{base}.html
$localization:
  path: /{locale}/documentation/components/{base}.html
$view: /views/detail/component-detail.j2
versions:
  - '0.2'
  - '0.1'
latest_version: '0.2'
```

In order to server the latest version with the old URL, we could create a nearly empty index.md file that would use a specific template to simply render the latest version.
Links from other files to that component should then point to the index.md when no specific version is chosen.
