### ISSUE TITLE
Blog post are hard to read on mobile due to large margins

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3041]
iPhone 5:

<img width="327" alt="Screen Shot 2019-09-30 at 08 01 13" src="https://user-images.githubusercontent.com/380472/65853267-30b0d300-e359-11e9-946a-fa9a1acb7857.png">

@westonruter could you take a look? Do you need CSS to be adjusted from our side?

**Comment by westonruter** [comment]
Finally got to this. Fixed with this CSS rule:

```css
@media (max-width:1024px) {
	/* Remove excessive horizontal padding on small screens */
	.entry-content>* {
		padding: 0;
	}
}
```

Now looks like:

![image](https://user-images.githubusercontent.com/134745/71298581-a49dbe80-233d-11ea-99f2-c764eda74ba2.png)

I applied this CSS patch via the Additional CSS in the WordPress Customizer. If applied on your side then it could be removed from being WordPress-specific.
