### ISSUE TITLE
Unused CSS for homepage

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3044]
It looks like a large portion of our CSS is unused:

<img width="930" alt="Screen Shot 2019-09-30 at 17 40 02" src="https://user-images.githubusercontent.com/380472/65894053-5c5ba980-e3a9-11e9-91aa-a5f7826dddc6.png">

We should investigate.

//cc @sebil @matthiasrohmer

**Comment by sebil** [comment]
After my research with several tools I get the result that all of the unused css we produce by our own on the home page is 3.7 KB in complete (minified).

```css
.-t .intro,.ap--section .intro{font-size:1rem;padding:0}.-t .intro *,.ap--section .intro *{font-size:inherit}.-t p small,.ap--section p small{font-size:.875rem}.-t figure figcaption,.ap--section figure figcaption{line-height:1.6rem;font-weight:400;color:#48525c;font-size:.8125rem;margin-top:.3em}.-t hr,.ap--section hr{height:1px;margin:.75em 0;background-color:#ebebf0;border:none}.-te .ap-m-ghost-frame-mobile{width:100%;margin:auto}.-ti.small{grid-column:5/12}.-ts.small{grid-column:14/21}.-tu{line-height:1.6rem;font-weight:400;color:#48525c;font-size:.875rem;margin-bottom:.5em}@media (min-width:768px){.-tk,.-tw,.-tx{grid-template-columns:repeat(4,1fr)}}.-tk .-tm,.-tw .-tm,.-tx .-tm{font-size:1rem}.-nc .hll{background-color:#49483e}.-nc .ch{color:#75715e}.-nc .cm{color:#75715e}.-nc .cp{color:#75715e}.-nc .cpf{color:#75715e}.-nc .gd{color:#f15a5a}.-nc .ge{font-style:italic}.-nc .gi{color:#a6e22e}.-nc .gs{font-weight:700}.-nc .gu{color:#75715e}.-nc .kc{color:#66d9ef}.-nc .kd{color:#66d9ef}.-nc .kn{color:#f15a5a}.-nc .kp{color:#66d9ef}.-nc .kr{color:#66d9ef}.-nc .kt{color:#66d9ef}.-nc .ow{color:#f15a5a}.-nc .mb{color:#ae81ff}.-nc .mf{color:#ae81ff}.-nc .mh{color:#ae81ff}.-nc .mi{color:#ae81ff}.-nc .mo{color:#ae81ff}.-nc .dl{color:#e6db74}.-nc .sx{color:#e6db74}.-nc .bp{color:#f8f8f2}.-nc .fm{color:#a6e22e}.-nc .vc{color:#f8f8f2}.-nc .vg{color:#f8f8f2}.-nc .vi{color:#f8f8f2}.-nc .vm{color:#f8f8f2}.ap-m-copy-left-small{grid-column:4/13}.ap-m-copy-left-xsmall{grid-column:6/13}.ap-m-copy-right-centered{width:100%;grid-column:16/21;margin:auto 0}.ap-m-copy-right-small{grid-column:11/20}@media (min-width:768px){.ap-m-copy-right-xsmall{grid-column:8/20}}@media (min-width:1024px){.ap-m-copy-right-xsmall{grid-column:12/20}}.ap-m-copy-center-small{grid-column:6/19;text-align:left}.ap-m-copy-center-medium{grid-column:4/22;text-align:left;max-width:100%}.-rt{overflow:hidden;margin-bottom:7em}@media (min-width:768px){.-rt{margin-bottom:8vw}}.-rt .ap-m-copy h3{margin-top:0}.-rl{fill:#fff;display:flex;font-size:initial;box-sizing:initial;justify-content:center;width:1.375em;height:1.375em;position:absolute;left:0;bottom:calc(100% + 1em);padding:.5em;border:1px solid #fff;border-radius:50%}@media (min-width:768px){.-rl{left:auto;bottom:auto;right:calc(100% + .75em);top:-.6em}}@media (min-width:1024px){.-rl{width:3em;height:3em;right:calc(100% + 1em);top:-1.5em;padding:1em;border-width:2px}}.-rh{line-height:1.6rem;font-weight:400;color:#48525c;font-size:1rem;color:#fff;margin-top:0;margin-bottom:.75em}@media (min-width:768px){.-rh{font-size:.875rem}}@media (min-width:1024px){.-rh{font-size:1.125rem}}.-ry{display:block;width:100%;height:1px;margin-bottom:.813em;background-color:#fafafc}@media (min-width:768px){.-ry{display:none}}@media (min-width:768px){.-rb{display:block}}.-rq{background:linear-gradient(225deg,#00dcc0 0,#005af0 75%)}.-rz{box-shadow:0 50px 100px 0 rgba(0,0,0,.25);z-index:1}@media (min-width:768px){.-rz{margin-left:55px}}.-ie{box-shadow:0 25px 50px 0 rgba(0,0,0,.21)}.-ir{grid-column:1/16}@media (min-width:1024px){.-ir{grid-column:1/12}}@media (min-width:1280px){.-ir{grid-column:1/10}}.-ii .-rw.principles{margin:50px 20px 100px 0}@media (min-width:1024px){.-iu{grid-column:3/10}}.has-banner+.-il.active~.ap--main{max-height:calc(100vh - 50px - 31px)}@media (max-width:1023px){.has-banner+.-il.active~.ap--main{max-height:calc(100vh - 55px - 31px)}}.has-banner~.ap-o-burger-menu{padding:calc(37px + 31px) 0 0 20px}.has-banner+.ap-o-burger-menu-label{top:calc(12px + 31px)}.has-banner+.ap-o-burger-menu.mainmenuopen~.ap--main{max-height:calc(100vh - 55px - 31px)}.-sw.-sx{text-decoration:underline}.-sx{font-weight:700;color:#005af0}.ap--header.has-banner{top:-31px}.-sj{color:#000;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}
```

Additionally there are a minimum of 9 KB that are not recognized initially because of different CSS media queries and elements that are hidden until interaction with amp-bind.
The `coverage` tool of chrome counts only CSS rules that are applying in the moment they are visible or 'existing'.
