### ISSUE TITLE
Make component intro table easily maintainable and visually appealing

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3168]
The current form of the component intro table has some hurdles. The biggest ones are: the information it holds is not reusable. It would be great if other documents could reuse information like supported layouts for a certain component to show them on an overview page or similar.

The other one is that it is maintained using real `<table>` tags instead of Markdown syntax which is error-prone.

An alternative we considered instead is transferring this information over to the frontmatter. See the following example for `amp-accordion`

```yaml
$category@: layout
formats:
  - websites
  - ads
  - email
teaser:
  text: Provides a way for viewers to have a glance at the outline of the content and jump to a section of their choice at will.
supported_layouts:
  - container
script: <script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
```

This would enable us to independently and consistently style and layout the intro table (or an alternative visual element) and for example do something like the following:

```jinja2
{% for layout of doc.supported_layouts %}
<a href="https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated/?format=websites#{{layout}}">{{ layout }}</a>
{% endfor %}
```

Another use case that this approach would help is outlined in #3167. By this change we could add another key to the frontmatter called `actions_events` with all available actions and events and then automatically generate a never outdated overview page for all available ones.
