### ISSUE TITLE
Sublists in blog posts have too much right padding on mobile devices

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4085]
I think this only applies to blog posts, since it involves rules scoped to `.entry-content`. But I could be wrong.

[This recent blog post](https://blog.amp.dev/2020/06/16/amp-camp-cross-origin-user-state-in-amp/) happens to contain a three-level list. Maybe that's not the best idea. But each `<ol>` comes with both `padding-left` and `padding-right`.  By the time you get to the third level, there's not much room left for the text.

I'd suggest that any sublist should have no `padding-right` on mobile. As in, for a one-level list, I think it looks nice, though you don't get much text per line. By the time you get to the second level, it's going to be a problem.

Here's a screenshot from Chrome emulating a Moto G4:

<img width="296" alt="Screen Shot 2020-06-16 at 4 18 04 PM" src="https://user-images.githubusercontent.com/29419498/84824288-aba44180-afed-11ea-9e01-3f917d675c33.png">

**Comment by patrickkettner** [comment]
@westonruter any chance you could check this out?

**Comment by westonruter** [comment]
I've added this:

```css
.entry-content ul, 
.entry-content ol {
	padding-right: 0;
}
```

So it's a bit improved on Moto G4:

![image](https://user-images.githubusercontent.com/134745/108802026-1b3ed900-754c-11eb-9e7a-f8779edc8eb4.png)

I've also added this:

```css
.entry-content li ul,
.entry-content li ol {
	margin-top: 0;
	margin-bottom: 0;
}
```

To prevent the margins between the nested lists:

![image](https://user-images.githubusercontent.com/134745/108802316-db2c2600-754c-11eb-8ab4-9db6cdcd2554.png)

**Comment by morsssss** [comment]
Thanks, @westonruter . This is much better!

I just experimented with adding this rule as well:

```css
.entry-content li ul {
  padding-left: 1.25em;
}
```

which decreases the left indent of the list's second level. What do you think?

**Comment by westonruter** [comment]
@morsssss I think the indentation should be consistent for all `ul`, so what I've done is add a rule which reduces the left padding to `1.25em` for all `ol` and `ul` when the viewport is `640px` or less:

```css
@media (max-width:640px) {
	.entry-content ul,
	.entry-content li ul,
	.entry-content ol,
	.entry-content li ol {
		padding-left: 1.25em;
	}
}
```

On larger viewports, the padding goes to `2.5em` in order to take advantage of the extra screen real estate.

How's that look now?
